/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.HashMap;
import javax.swing.JOptionPane;
import logica.Elemento;
import logica.Tablero;
import logica.Usuario;

/**
 *
 * @author Cristina
 */
public class TableroJuego extends javax.swing.JFrame {
    //Atributos
    private RegistroUsuario rg;
    HashMap<String, Usuario> hmap = null;
    Usuario usr;
    Tablero tab;
    
    //Constructor
    /**
     * Creates new form Tablero
     * @param t
     * @param u
     * @param ventana
     */
    public TableroJuego(Tablero t, Usuario u, RegistroUsuario ventana) {
        rg = ventana;
        rg.setVisible(false);
        this.setVisible(true);
        this.tab = t;
        this.usr = u;
        initComponents();
        
        try {
            try (ObjectInputStream leerFichero = new ObjectInputStream(new FileInputStream("datosJuego.dat"))) {
                hmap = (HashMap) leerFichero.readObject();
            }
        } catch (IOException | ClassNotFoundException e) {
            System.out.println(e.getMessage());
        }
        
        tab.inicializarJuego();
    }
    
    //Metodos
    /**
     *
     * @param elementos
     */
    public void actualizarTablero(Elemento[][] elementos) {
        for (int i = 0; i < 7; i++) {
            for (int j = 0; j < 7; j++) {
                jTableTablero.setValueAt(elementos[i][j], i, j);
            }
        }
    }
    
    public void finJuego (){
        if (tab.controlJuego() == 0) {
            usr.setPuntos(tab.puntos());
            usr.setPuntosTotales(usr.getPuntosTotales() + usr.getPuntos());
            usr.setPartidaGanada(usr.getPartidaGanada()+ 1);
            usr.setPartidaTotal(usr.getPartidaGanada() + usr.getPartidaPerdida());
            hmap.put(usr.getDni(), usr);
            try {
                try (ObjectOutputStream escribirFichero = new ObjectOutputStream(new FileOutputStream("datosJuego.dat"))) {
                    escribirFichero.writeObject(hmap);
                }
            } catch (IOException e) {
                System.out.println(e.getMessage());
            }
            JOptionPane.showMessageDialog(this, "HAS GANADO", "Partida Finalizada", JOptionPane.INFORMATION_MESSAGE);
            dispose();
            Estadistica e = new Estadistica();
            e.setVisible(true);
        }
        else if (tab.controlJuego() == 1) {
            usr.setPuntos(tab.puntos());
            usr.setPuntosTotales(usr.getPuntosTotales() + usr.getPuntos());
            usr.setPartidaPerdida(usr.getPartidaPerdida()+ 1);
            usr.setPartidaTotal(usr.getPartidaGanada() + usr.getPartidaPerdida());
            hmap.put(usr.getDni(), usr);
            try {
                try (ObjectOutputStream escribirFichero = new ObjectOutputStream(new FileOutputStream("datosJuego.dat"))) {
                    escribirFichero.writeObject(hmap);
                }
            } catch (IOException e) {
                System.out.println(e.getMessage());
            }
            JOptionPane.showMessageDialog(this, "HAS PERDIDO", "Partida Finalizada", JOptionPane.INFORMATION_MESSAGE);
            dispose();
            Estadistica e = new Estadistica();
            e.setVisible(true);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTablero = new javax.swing.JTable();
        jButtonGirasol = new javax.swing.JButton();
        jButtonLGisante = new javax.swing.JButton();
        jButtonNuez = new javax.swing.JButton();
        jButtonTurno = new javax.swing.JButton();
        jLabelTurno = new javax.swing.JLabel();
        jLabelSoles = new javax.swing.JLabel();
        jTextFieldTurno = new javax.swing.JTextField();
        jTextFieldSoles = new javax.swing.JTextField();
        jButtonEstadisticas = new javax.swing.JButton();
        jButtonAyuda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(3, 55, 37));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);

        jTableTablero.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(12, 36, 17), 1, true), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        jTableTablero.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTableTablero.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTablero.setMaximumSize(new java.awt.Dimension(2147483647, 350));
        jTableTablero.setMinimumSize(new java.awt.Dimension(105, 350));
        jTableTablero.setPreferredSize(new java.awt.Dimension(525, 349));
        jTableTablero.setRowHeight(50);
        jTableTablero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTableroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTablero);
        if (jTableTablero.getColumnModel().getColumnCount() > 0) {
            jTableTablero.getColumnModel().getColumn(0).setResizable(false);
            jTableTablero.getColumnModel().getColumn(1).setResizable(false);
            jTableTablero.getColumnModel().getColumn(2).setResizable(false);
            jTableTablero.getColumnModel().getColumn(3).setResizable(false);
            jTableTablero.getColumnModel().getColumn(4).setResizable(false);
            jTableTablero.getColumnModel().getColumn(5).setResizable(false);
            jTableTablero.getColumnModel().getColumn(6).setResizable(false);
        }
        jTableTablero.getAccessibleContext().setAccessibleParent(null);

        jButtonGirasol.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButtonGirasol.setText("GIRASOL");
        jButtonGirasol.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 169, 0), 1, true));
        jButtonGirasol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGirasolActionPerformed(evt);
            }
        });

        jButtonLGisante.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButtonLGisante.setText("LANZA GUISANTES");
        jButtonLGisante.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(65, 255, 71), 1, true));
        jButtonLGisante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLGisanteActionPerformed(evt);
            }
        });

        jButtonNuez.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButtonNuez.setText("NUEZ");
        jButtonNuez.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(130, 86, 0), 1, true));
        jButtonNuez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuezActionPerformed(evt);
            }
        });

        jButtonTurno.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonTurno.setText("Pasar Turno");
        jButtonTurno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTurnoActionPerformed(evt);
            }
        });

        jLabelTurno.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabelTurno.setText("TURNO:");

        jLabelSoles.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabelSoles.setText("SOLES:");

        jTextFieldTurno.setEditable(false);
        jTextFieldTurno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldTurno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTurno.setText("0");

        jTextFieldSoles.setEditable(false);
        jTextFieldSoles.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldSoles.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSoles.setText("50");

        jButtonEstadisticas.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jButtonEstadisticas.setText("E S T A D I S T I C A S");
        jButtonEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEstadisticasActionPerformed(evt);
            }
        });

        jButtonAyuda.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jButtonAyuda.setText("A Y U D A");
        jButtonAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAyudaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButtonGirasol, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButtonLGisante, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButtonNuez, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButtonTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAyuda))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelSoles)
                            .addComponent(jTextFieldTurno)
                            .addComponent(jTextFieldSoles))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGirasol, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLGisante)
                    .addComponent(jButtonNuez)
                    .addComponent(jButtonTurno))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabelTurno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabelSoles)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEstadisticas)
                    .addComponent(jButtonAyuda))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTableTableroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTableroMouseClicked

    }//GEN-LAST:event_jTableTableroMouseClicked

    private void jButtonGirasolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGirasolActionPerformed
        //Agregar girasol
        if (tab.getSoles() >= 20) {
            int columna = jTableTablero.getSelectedColumn();
            int fila = jTableTablero.getSelectedRow();
            String planta = "G";
            
            tab.setTurno(tab.getTurno() + 1);
            tab.agregarPlanta(planta, fila, columna);
            tab.quitarVidaZombi();
            tab.avanzaZombi();
            tab.agregarZombie();
            
            actualizarTablero(tab.getElementos());
            jTextFieldTurno.setText(tab.getTurno() + "");
            jTextFieldSoles.setText(tab.getSoles()+ "");
        } else {
            JOptionPane.showMessageDialog(this, "¡ No tienes suficientes soles !", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
        finJuego();
        
    }//GEN-LAST:event_jButtonGirasolActionPerformed

    private void jButtonLGisanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLGisanteActionPerformed
        //Agregar lanza guisante
        if (tab.getSoles() >= 50) {
            int columna = jTableTablero.getSelectedColumn();
            int fila = jTableTablero.getSelectedRow();
            String planta = "L";
            
            tab.setTurno(tab.getTurno() + 1);
            tab.agregarPlanta(planta, fila, columna);
            tab.quitarVidaZombi();
            tab.avanzaZombi();
            tab.agregarZombie();
            
            actualizarTablero(tab.getElementos());
            jTextFieldTurno.setText(tab.getTurno() + "");
            jTextFieldSoles.setText(tab.getSoles()+ "");
        } else {
            JOptionPane.showMessageDialog(this, "¡ No tienes suficientes soles !", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
        finJuego();
    }//GEN-LAST:event_jButtonLGisanteActionPerformed

    private void jButtonNuezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuezActionPerformed
        //Agregar Nuez
        if (tab.getSoles() >= 50) {
            int columna = jTableTablero.getSelectedColumn();
            int fila = jTableTablero.getSelectedRow();
            String planta = "N";
            
            tab.setTurno(tab.getTurno() + 1);
            tab.agregarPlanta(planta, fila, columna);
            tab.quitarVidaZombi();
            tab.avanzaZombi();
            tab.agregarZombie();
            
            actualizarTablero(tab.getElementos());
            jTextFieldTurno.setText(tab.getTurno() + "");
            jTextFieldSoles.setText(tab.getSoles() + "");
        } else {
            JOptionPane.showMessageDialog(this, "¡ No tienes suficientes soles !", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonNuezActionPerformed

    private void jButtonTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTurnoActionPerformed
        //Pasar turno
        tab.setTurno(tab.getTurno() + 1);
        tab.generarSoles();
        tab.quitarVidaZombi();
        tab.avanzaZombi();
        tab.agregarZombie();
        
        actualizarTablero(tab.getElementos());
        jTextFieldTurno.setText(tab.getTurno() + "");
        jTextFieldSoles.setText(tab.getSoles() + "");
        
        finJuego();
    }//GEN-LAST:event_jButtonTurnoActionPerformed

    private void jButtonAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAyudaActionPerformed
        JOptionPane.showMessageDialog(this, "\n- Boton Girasol: agregar Girasol al tablero\n"
                + "- Boton LanzaGuisantes: agregar LanzaGuisantes al tablero\n"
                + "- Boton Nuez: agregar una Nuez al tablero\n"
                + "- Boton Pasar Turno: Pasar Turno", "AYUDA", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonAyudaActionPerformed

    private void jButtonEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEstadisticasActionPerformed
        Estadistica e  = new Estadistica();
    }//GEN-LAST:event_jButtonEstadisticasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAyuda;
    private javax.swing.JButton jButtonEstadisticas;
    private javax.swing.JButton jButtonGirasol;
    private javax.swing.JButton jButtonLGisante;
    private javax.swing.JButton jButtonNuez;
    private javax.swing.JButton jButtonTurno;
    private javax.swing.JLabel jLabelSoles;
    private javax.swing.JLabel jLabelTurno;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTablero;
    private javax.swing.JTextField jTextFieldSoles;
    private javax.swing.JTextField jTextFieldTurno;
    // End of variables declaration//GEN-END:variables
}
